spring.application.name=api-service

server.port=${PORT:8081}

app.user-service.url=${APP_USER_SERVICE_URL}
app.movie-service.url=${APP_MOVIE_SERVICE_URL}
app.review-service.url=${APP_REVIEW_SERVICE_URL}
app.forum-service.url=${APP_FORUM_SERVICE_URL}