spring.application.name=api-service

server.port=${PORT:8081}

app.user-service.url=${APP_USER_SERVICE_URL:http://localhost:8082}
app.movie-service.url=${APP_MOVIE_SERVICE_URL:http://localhost:8083}
app.review-service.url=${APP_REVIEW_SERVICE_URL:http://localhost:8084}
app.forum-service.url=${APP_FORUM_SERVICE_URL:http://localhost:8085}