spring.application.name=forum-service

server.port=${PORT:8085}

spring.datasource.url=${FOURM_DB_URL}
spring.datasource.username=${FOURM_DB_USERNAME}
spring.datasource.password=${FOURM_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.ca.yorku.eecs4314group12.forum=INFO