spring.application.name=forum-service

server.port=8085

spring.datasource.url=jdbc:postgresql://postgres:5432/forum_service
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.ca.yorku.eecs4314group12.forum=INFO