spring.application.name=review-service

server.port=${PORT:8084}

# PostgreSQL Database Configuration
spring.datasource.url=${REVIEW_DB_URL}
spring.datasource.username=${REVIEW_DB_USERNAME}
spring.datasource.password=${REVIEW_DB_PASSWORD}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.ca.yorku.eecs4314group12.review=INFO
